# SQL Interview Questions  - Quiz


## Introduction

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

What are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________
TEXT, INTEGER, BLOB, and REAL are the four main datatypes in SQLite3. Other common types from other kinds of SQL can be used, as these four main types are more categories through which other datatypes can be brought into SQL.



## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Primary keys are the keys a table uses to index itself, and they are necessarily one-to-one. Foreign keys are indexes that point to individual data in a separate table, and are not necessarily exclusive to any one element outside of their home tables (i.e., the same foreign key could belong to many rows in a table where it isn't the primary key).



## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
One-to-one relationships is one where one element from a first table is matched to exactly one element from a secon d table. 

A one-to-many relationship is one in which a single element from a first table has a relationship (a shared index) with potentially many elements from a second table, the way a single year could point to as many as 366 days.

A many-to-many relationship is one in which a single element from a first table could share an index with potentially many elements from a second table, but at the same time, several elements from the first table could point to a single element in the second table. An example might be the relationship between teachers and students at a school. While a single teacher might be matched with many students (e.g., a class of 30), several teachers could also point to a single student (e.g., Judy is indexed by Mrs. Wright, Mrs. Frank, and Mr. Smith).


## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
All JOINs are a method of combining two tables using a common feature. If the table includes foreign keys, those can be used to call JOINs over, as they point directly to the elements in another table. Once a common key has been specified between two tables, four different JOINs can be called to different affects. INNER JOINs collect only the elements with IDs that the two tables have in common; OUTER JOINs combine all elements from both tables (and if an index is missing from one table, the columns in the resulting JOIN for that row will be filled with NaN or NULL); LEFT JOINs collect all elements from the left table, and any elements with matching IDs from the right table; and RIGHT JOINs collect all elements from the right table and any elements with matching IDs from the left table.


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
    To make an analogy, data are like a field of sheep, and a GROUP BY statement is akin to building fences around groups of data that share the same value for a given column. Aggregate functions, then, are like the sheep dogs released into those fenced in areas: they consolidate, but only within their respective fences. So, for an example, if you GROUP BY one column, car model, and then Aggregate for the maximum value of a second column, perhaps yearly revenue, you'll get a table showing the year with the highest revenue for each car model.



## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________
Unlike a one-to-one JOIN, where one element from a first table is combined with exactly one element from a second, in a many-to-many JOIN an Associative Entity (JOIN Table) keeps track of the network of relationships between two tables.



## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.